export const ROLE_CATEGORIES = {
  ALL: 'ALL',
  REGULAR_MEETING: 'REGULAR_MEETING',
  SPECIAL_MEETING: 'SPECIAL_MEETING',
  CONTEST_MEETING: 'CONTEST_MEETING',
  REGULAR_AND_SPECIAL: 'REGULAR_AND_SPECIAL'
};

export const ROLE_CATEGORY_LABELS = {
  [ROLE_CATEGORIES.ALL]: 'All Roles',
  [ROLE_CATEGORIES.REGULAR_MEETING]: 'Regular Meeting',
  [ROLE_CATEGORIES.SPECIAL_MEETING]: 'Special Meeting',
  [ROLE_CATEGORIES.CONTEST_MEETING]: 'Contest Meeting',
  [ROLE_CATEGORIES.REGULAR_AND_SPECIAL]: 'Regular and Special Meeting'
};
