export const ROLE_CATEGORIES = {
  ALL: 'ALL',
  REGULAR_MEETING: 'REGULAR_MEETING',
  SPECIAL_MEETING: 'SPECIAL_MEETING',
  CONTEST_MEETING: 'CONTEST_MEETING_ONLY',
  REGULAR_AND_SPECIAL: 'REGULAR_AND_SPECIAL_MEETINGS',
  SHARED_ALL_MEETINGS: 'SHARED_ALL_MEETINGS'
};

export const ROLE_CATEGORY_LABELS = {
  [ROLE_CATEGORIES.ALL]: 'All Roles',
  [ROLE_CATEGORIES.REGULAR_MEETING]: 'Regular Meeting',
  [ROLE_CATEGORIES.SPECIAL_MEETING]: 'Special Meeting',
  [ROLE_CATEGORIES.CONTEST_MEETING]: 'Contest Meeting',
  [ROLE_CATEGORIES.REGULAR_AND_SPECIAL]: 'Regular & Special',
  [ROLE_CATEGORIES.SHARED_ALL_MEETINGS]: 'All Meetings',
  // Add direct mappings for API values
  'CONTEST_MEETING_ONLY': 'Contest Meeting',
  'REGULAR_AND_SPECIAL_MEETINGS': 'Regular & Special',
  'SHARED_ALL_MEETINGS': 'All Meetings'
};

// Map UI category values to API category values
export const CATEGORY_MAPPING = {
  [ROLE_CATEGORIES.REGULAR_MEETING]: ['REGULAR_MEETING', 'REGULAR_AND_SPECIAL_MEETINGS', 'SHARED_ALL_MEETINGS'],
  [ROLE_CATEGORIES.SPECIAL_MEETING]: ['SPECIAL_MEETING', 'REGULAR_AND_SPECIAL_MEETINGS', 'SHARED_ALL_MEETINGS'],
  [ROLE_CATEGORIES.CONTEST_MEETING]: ['CONTEST_MEETING_ONLY', 'SHARED_ALL_MEETINGS'],
  [ROLE_CATEGORIES.REGULAR_AND_SPECIAL]: ['REGULAR_AND_SPECIAL_MEETINGS', 'SHARED_ALL_MEETINGS'],
  [ROLE_CATEGORIES.SHARED_ALL_MEETINGS]: ['SHARED_ALL_MEETINGS']
};
