spring.application.name=toastMasters
spring.datasource.url=jdbc:postgresql://localhost:5432/ToastMaster
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
